name: Deploy repository to Github Pages
# This action is from the stashapp/CommunityScrapers repo https://github.com/stashapp/CommunityScrapers/blob/stable/.github/workflows/deploy.yml

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: '0'

    - name: Fetch all branches
      run: git fetch --all

    - name: Run buildScraper script
      run: |
        chmod +x build_site.sh
        ./build_site.sh

    - uses: actions/upload-pages-artifact@v3
      with:
        path: ./stable

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
