name: Deploy repository to Github Pages
# This action is from the stashapp/CommunityScrapers repo https://github.com/stashapp/CommunityScrapers/blob/stable/.github/workflows/deploy.yml
env:
  BRANCH_NAME: ${{ github.base_ref || github.ref_name }}

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        path: main
        ref: ${{ env.BRANCH_NAME }}
        fetch-depth: '0'
    - run: |
        cd main
        if [ "${{ env.BRANCH_NAME }}" = "main" ]; then
          ./build_site.sh ../_site/stable
        else
          ./build_site.sh ../_site/${{ env.BRANCH_NAME }}
        fi
    - uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
